<?php

namespace Database\Seeders;

use App\Models\SolutionProduct;
use Illuminate\Database\Seeder;

class SolutionProductSeeder extends Seeder
{
    /**
     * Seed the Solution Studio products shown in the public "Solution Studio"
     * showcase. Idempotent: safe to run on every deploy against an already
     * populated production database.
     */
    public function run(): void
    {
        $solutions = [
            [
                'slug' => 'erp',
                'category' => 'Enterprise ERP & Commerce',
                'badge' => 'Omnichannel Core',
                'title' => 'DevCenterPoint ERP & Storefront',
                'tagline' => 'Full-stack enterprise ERP integrated with an omnichannel storefront, live inventory sync, and POS sales workflows.',
                'icon_name' => 'Globe',
                'mockup_title' => 'DevCenterPoint ERP • Enterprise Control Portal',
                'live_url' => 'https://demoerp.devcenterpoint.com',
                'admin_url' => 'https://demoerp.devcenterpoint.com/login',
                'demo_username' => 'Admin',
                'demo_password' => '12345678',
                'demo_role' => 'Enterprise Administrator',
                'stats' => [
                    ['label' => 'Active SKU Matrix', 'value' => '18,450+', 'change' => 'Multi-hub sync', 'trend' => 'up'],
                    ['label' => 'Platform Uptime', 'value' => '99.98%', 'change' => 'Zero stock drift', 'trend' => 'up'],
                    ['label' => 'Order Processing SLA', 'value' => '0.38s', 'change' => 'Redis lock engine', 'trend' => 'up'],
                ],
                'activity_logs' => [
                    ['time' => 'Just now', 'event' => 'Enterprise warehouse batch dispatch completed (SKU #4892)', 'badge' => 'Fulfillment'],
                    ['time' => '2m ago', 'event' => 'Omnichannel checkout reconciled via Stripe & Gateway', 'badge' => 'Settlement'],
                    ['time' => '5m ago', 'event' => 'Multi-tier safety stock threshold auto-replenished', 'badge' => 'Inventory'],
                ],
                'business_outcomes' => [
                    'speedToMarket' => '6 to 8 weeks to full deployment',
                    'impact' => '100% elimination of double-allocations',
                    'security' => 'Optimistic concurrency & RBAC audit logs',
                ],
                'client_benefits' => [
                    'Unified stock visibility preventing stockouts and overselling across all sales channels',
                    'High-density order tables engineered for rapid keyboard navigation & zero fatigue',
                    'Automated courier routing rules based on proximity, stock level, and courier SLAs',
                ],
                'deliverables' => [
                    'Omnichannel storefront + back-office ERP',
                    'Multi-warehouse inventory synchronization engine',
                    'Batch order manifest & shipping label generator',
                    '100% full source code repository handover',
                ],
                'sample_action_label' => 'Simulate POS Inventory Dispatch',
                'sample_action_toast' => '✓ Order #DCP-8842 allocated across 3 warehouses in 34ms! Live stock locked.',
                'display_order' => 1,
                'is_active' => true,
            ],
            [
                'slug' => 'roadsafety',
                'category' => 'Civic Ops & Safety Platform',
                'badge' => 'Civic OS',
                'title' => 'Road Safety Movement',
                'tagline' => 'Central operational platform coordinating nationwide civic campaigns, verified member directories, and public safety emergency alerts.',
                'icon_name' => 'ShieldAlert',
                'mockup_title' => 'Road Safety Movement • Civic Coordination Portal',
                'live_url' => 'https://roadsafetymovement.org',
                'admin_url' => 'https://roadsafetymovement.org',
                'demo_username' => 'Coordinator Demo',
                'demo_password' => '12345678',
                'demo_role' => 'Campaign Coordinator',
                'stats' => [
                    ['label' => 'Active Members', 'value' => '12,400+', 'change' => 'Verified advocates', 'trend' => 'up'],
                    ['label' => 'Dispatch Latency', 'value' => '1.2s', 'change' => 'Emergency broadcast', 'trend' => 'up'],
                    ['label' => 'Resolution Rate', 'value' => '94.8%', 'change' => 'Community response SLA', 'trend' => 'up'],
                ],
                'activity_logs' => [
                    ['time' => 'Just now', 'event' => 'Emergency highway awareness campaign dispatched to 450 volunteers', 'badge' => 'Dispatch'],
                    ['time' => '3m ago', 'event' => 'New civic advocate identity badge verified and issued', 'badge' => 'Verified'],
                    ['time' => '8m ago', 'event' => 'Community incident report triaged by regional coordinator', 'badge' => 'Triage'],
                ],
                'business_outcomes' => [
                    'speedToMarket' => '3 to 5 weeks for civic / org setup',
                    'impact' => '90% faster emergency volunteer mobilization',
                    'security' => 'Strict RBAC & encrypted member directory',
                ],
                'client_benefits' => [
                    'Verified member directory with digital role credentials and tamper-proof security badges',
                    'Campaign dispatch console for sub-second community broadcast alerts and volunteer mobilization',
                    'High-contrast mobile interface optimized for on-the-ground volunteer coordination',
                ],
                'deliverables' => [
                    'Member registration & digital ID verification portal',
                    'Real-time campaign logistics dispatch & coordinator workflow',
                    'Public announcement and incident report management engine',
                    'Operational impact analytics dashboard for organizational governance',
                ],
                'sample_action_label' => 'Dispatch Campaign Alert',
                'sample_action_toast' => '🚨 Safety Alert dispatched! 450 verified community volunteers mobilized in 1.2s.',
                'display_order' => 2,
                'is_active' => true,
            ],
            [
                'slug' => 'traccar',
                'category' => 'IoT & Fleet Telematics',
                'badge' => 'Fleet OS',
                'title' => 'Traccar GPS Telematics Deployment',
                'tagline' => 'Containerized open-source GPS tracking and telematics stack processing high-frequency hardware IoT packets with real-time geofence boundaries.',
                'icon_name' => 'Radio',
                'mockup_title' => 'Traccar Telematics • Live Fleet Vector Canvas',
                'live_url' => 'https://github.com/beingmushfiq',
                'admin_url' => null,
                'demo_username' => 'Fleet Lead',
                'demo_password' => '12345678',
                'demo_role' => 'Fleet Supervisor',
                'stats' => [
                    ['label' => 'Connected Assets', 'value' => '850+ Fleet', 'change' => 'Live GPS telemetry', 'trend' => 'up'],
                    ['label' => 'TCP Packet Ingestion', 'value' => '3,200/s', 'change' => 'GT06 / J1939 streams', 'trend' => 'up'],
                    ['label' => 'Spatial Precision', 'value' => '< 5 meters', 'change' => 'PostGIS polygon bounds', 'trend' => 'up'],
                ],
                'activity_logs' => [
                    ['time' => 'Just now', 'event' => 'Vehicle #F-104 entered Depot Zone Alpha (Geofence alert cleared)', 'badge' => 'Geofence'],
                    ['time' => '2m ago', 'event' => 'Harsh braking event detected on Highway A3 — Telemetry logged', 'badge' => 'Telematics'],
                    ['time' => '6m ago', 'event' => 'High-frequency TCP packet stream synced with PostGIS cluster', 'badge' => 'Data Stream'],
                ],
                'business_outcomes' => [
                    'speedToMarket' => '4 to 6 weeks for Docker fleet stack',
                    'impact' => '32% reduction in fuel waste & unauthorized idling',
                    'security' => 'End-to-end encrypted TCP telemetry pipeline',
                ],
                'client_benefits' => [
                    'Live fleet tracking map with 60fps vector canvas rendering hundreds of concurrent assets',
                    'Automated geofence boundary alerts sent instantly to dispatch supervisors via WebSockets',
                    'Historical trip playback with speed graphs, engine status, and driver safety scoring',
                ],
                'deliverables' => [
                    'Containerized Docker telematics server deployment',
                    'High-throughput TCP packet parser for automotive trackers',
                    'Interactive Mapbox vector map client with route replay',
                    'Real-time WebSocket event broadcaster and alert rules engine',
                ],
                'sample_action_label' => 'Simulate Telemetry Ping',
                'sample_action_toast' => '📡 Telemetry Ping received! Vehicle #F-104 location & speed updated on canvas in 14ms.',
                'display_order' => 3,
                'is_active' => true,
            ],
            [
                'slug' => 'slicemart',
                'category' => 'Retail & Inventory FMS',
                'badge' => 'Retail Engine',
                'title' => 'Slice Mart FMS',
                'tagline' => 'Grocery and retail floor management platform enabling instant barcode scanning, shelf-level stock counts, and POS inventory checkout.',
                'icon_name' => 'ShoppingCart',
                'mockup_title' => 'Slice Mart • Retail Floor & Stock Controller',
                'live_url' => 'https://slice-mart-fms.vercel.app',
                'admin_url' => null,
                'demo_username' => 'Store Manager',
                'demo_password' => '12345678',
                'demo_role' => 'Floor Manager',
                'stats' => [
                    ['label' => 'Tracked Shelf SKUs', 'value' => '6,800+', 'change' => 'Floor inventory mapped', 'trend' => 'up'],
                    ['label' => 'Barcode Scan Speed', 'value' => '180ms', 'change' => 'Camera PWA decode', 'trend' => 'up'],
                    ['label' => 'Audit Discrepancy', 'value' => '< 0.02%', 'change' => 'Real-time sync', 'trend' => 'up'],
                ],
                'activity_logs' => [
                    ['time' => 'Just now', 'event' => 'Aisle 4 shelf count updated via barcode scanner (Batch #902)', 'badge' => 'Stock Audit'],
                    ['time' => '1m ago', 'event' => 'Cashier checkout register #2 decremented 14 item units', 'badge' => 'POS Sync'],
                    ['time' => '5m ago', 'event' => 'Low stock safety reorder trigger dispatched to supplier portal', 'badge' => 'Auto-Order'],
                ],
                'business_outcomes' => [
                    'speedToMarket' => '3 to 5 weeks for store deployment',
                    'impact' => '85% faster physical inventory audit cycles',
                    'security' => 'Offline-first PWA with resilient cloud sync',
                ],
                'client_benefits' => [
                    'Instant barcode camera scanning turning any smartphone or tablet into a rugged inventory terminal',
                    'Shelf-level inventory visibility preventing out-of-stock items on retail sales floors',
                    'Unified cashier POS integration ensuring zero sync latency between sales and warehouse',
                ],
                'deliverables' => [
                    'Progressive Web App (PWA) barcode scanner client',
                    'Store floor layout & multi-shelf SKU management console',
                    'Automated stock replenishment notification webhook service',
                    'Real-time POS checkout integration ledger',
                ],
                'sample_action_label' => 'Simulate Barcode SKU Audit',
                'sample_action_toast' => '📦 Barcode #079342 scanned! Aisle 4 shelf stock confirmed & ledger synchronized in 28ms.',
                'display_order' => 4,
                'is_active' => true,
            ],
            [
                'slug' => 'leadlayer',
                'category' => 'B2B Sales & Pipeline CRM',
                'badge' => 'Automated Pipeline',
                'title' => 'LeadLayer System Architecture',
                'tagline' => 'High-velocity webhook ingestion pipeline and CRM automation tool designed for automated lead qualification and round-robin sales distribution.',
                'icon_name' => 'Layers',
                'mockup_title' => 'LeadLayer CRM • Pipeline Automation Engine',
                'live_url' => 'https://github.com/beingmushfiq',
                'admin_url' => null,
                'demo_username' => 'Sales Director',
                'demo_password' => '12345678',
                'demo_role' => 'Sales Director',
                'stats' => [
                    ['label' => 'Webhooks Ingested', 'value' => '45,000+', 'change' => 'Multi-channel intake', 'trend' => 'up'],
                    ['label' => 'Ingestion Latency', 'value' => '0.12s', 'change' => 'Webhook to Kanban queue', 'trend' => 'up'],
                    ['label' => 'Conversion Lift', 'value' => '+38%', 'change' => 'Fast-response routing', 'trend' => 'up'],
                ],
                'activity_logs' => [
                    ['time' => 'Just now', 'event' => 'Enterprise inbound lead parsed and scored (Fit Score: 94/100)', 'badge' => 'AI Scoring'],
                    ['time' => '2m ago', 'event' => 'Round-robin assigned lead #L-8392 to Account Exec Sarah T.', 'badge' => 'Routing'],
                    ['time' => '7m ago', 'event' => 'Deal stage transitioned to Contract Review via Zapier webhook', 'badge' => 'Kanban'],
                ],
                'business_outcomes' => [
                    'speedToMarket' => '2 to 4 weeks to deploy CRM workflows',
                    'impact' => '4x faster lead response time for sales teams',
                    'security' => 'Encrypted OAuth2 tokens & webhook HMAC checks',
                ],
                'client_benefits' => [
                    'Sub-second webhook intake connecting forms, landing pages, and ad channels with zero dropped leads',
                    'Intuitive drag-and-drop Kanban interface with optimistic UI updates and zero lag',
                    'Automated criteria-based and round-robin lead allocation preventing sales bottleneck',
                ],
                'deliverables' => [
                    'Multi-channel webhook receiver with HMAC signature validation',
                    'Interactive Kanban deal pipeline with custom stages',
                    'Automated email sequence and task assignment triggers',
                    'Deal velocity & sales forecasting analytics suite',
                ],
                'sample_action_label' => 'Simulate Inbound Lead Ingestion',
                'sample_action_toast' => '⚡ New Enterprise Lead ingested via webhook! Scored 94/100 & assigned to rep in 35ms.',
                'display_order' => 5,
                'is_active' => true,
            ],
            [
                'slug' => 'ngodemo',
                'category' => 'Social Impact & Crowdfunding',
                'badge' => 'Civic Impact',
                'title' => 'NGO Demo (DCP)',
                'tagline' => 'Donation drives, transparent fund tracking, and campaign management platform built for NGOs and civic organizations.',
                'icon_name' => 'Heart',
                'mockup_title' => 'NGO Platform • Transparent Fund Allocation Ledger',
                'live_url' => 'https://ngodemo-dcp.vercel.app',
                'admin_url' => null,
                'demo_username' => 'Fund Auditor',
                'demo_password' => '12345678',
                'demo_role' => 'Transparent Fund Auditor',
                'stats' => [
                    ['label' => 'Disbursed Grants', 'value' => '$420,000+', 'change' => '100% verified trace', 'trend' => 'up'],
                    ['label' => 'Audit Transparency', 'value' => '100%', 'change' => 'Public ledger verification', 'trend' => 'up'],
                    ['label' => 'Donor Retention', 'value' => '88.5%', 'change' => 'Live impact reporting', 'trend' => 'up'],
                ],
                'activity_logs' => [
                    ['time' => 'Just now', 'event' => 'Emergency flood relief allocation verified and logged to public ledger', 'badge' => 'Disbursement'],
                    ['time' => '4m ago', 'event' => 'Micro-donation of $250 reconciled via instant payment gateway', 'badge' => 'Donation'],
                    ['time' => '9m ago', 'event' => 'Community impact photo report published to active donor feed', 'badge' => 'Story'],
                ],
                'business_outcomes' => [
                    'speedToMarket' => '3 to 5 weeks for civic campaign launch',
                    'impact' => '100% transparent audit trail for every dollar',
                    'security' => 'Cryptographic transaction ledger verification',
                ],
                'client_benefits' => [
                    'Complete public transparency that builds unbreakable donor trust and boosts repeat gifts',
                    'Integrated donation checkout supporting international cards and local mobile wallets',
                    'Automated tax receipts and personalized impact updates sent to donors on milestone completion',
                ],
                'deliverables' => [
                    'Public donation portal with multi-currency checkout',
                    'Transparent fund allocation ledger & reporting dashboard',
                    'Volunteer campaign management & event coordination suite',
                    'Automated donor receipt generation & email dispatch',
                ],
                'sample_action_label' => 'Simulate Transparent Grant Allocation',
                'sample_action_toast' => '💙 Grant of $1,500 allocated to Community Clean Water project! Public audit ledger updated.',
                'display_order' => 6,
                'is_active' => true,
            ],
            [
                'slug' => 'aistudio',
                'category' => 'Applied AI & Workflow Hub',
                'badge' => 'Explainable AI',
                'title' => 'DevCenterPoint AI Studio',
                'tagline' => 'Dedicated research & engineering hub showcasing explainable machine learning models, XGBoost inference, and workflow automation.',
                'icon_name' => 'Sparkles',
                'mockup_title' => 'DevCenterPoint AI Studio • Applied AI Hub',
                'live_url' => 'https://devcenterpoint.ai.studio',
                'admin_url' => null,
                'demo_username' => 'Data Scientist',
                'demo_password' => '12345678',
                'demo_role' => 'ML Research Lead',
                'stats' => [
                    ['label' => 'Weekly Hours Saved', 'value' => '1,480 hrs', 'change' => 'Automated LLM pipelines', 'trend' => 'up'],
                    ['label' => 'Inference Latency', 'value' => '0.18s', 'change' => 'FastAPI streaming', 'trend' => 'up'],
                    ['label' => 'Model Precision', 'value' => '99.4%', 'change' => 'Domain fine-tuning', 'trend' => 'up'],
                ],
                'activity_logs' => [
                    ['time' => 'Just now', 'event' => 'Autonomous webhook router parsed 120 client leads', 'badge' => 'Agentic'],
                    ['time' => '3m ago', 'event' => 'SHAP feature importance graph computed for career model', 'badge' => 'Explainable'],
                    ['time' => '6m ago', 'event' => 'Clinical screening assessment PDF compiled and dispatched', 'badge' => 'DocGen'],
                ],
                'business_outcomes' => [
                    'speedToMarket' => '3 to 5 weeks for domain AI integration',
                    'impact' => '65% reduction in manual data entry & triage',
                    'security' => 'Zero data leakage / Private dedicated inference',
                ],
                'client_benefits' => [
                    'Answers customer and staff questions 24/7 with deep context understanding',
                    'Explainable AI models backed by mathematical feature attribution (SHAP)',
                    'Your private business data is protected and never used to train public models',
                ],
                'deliverables' => [
                    'Custom domain LLM pipeline & retrieval system (RAG)',
                    'FastAPI C-accelerated inference microservices',
                    'Automated document processing & PDF extraction engine',
                    'Monitoring, hallucination guards, and token usage optimization',
                ],
                'sample_action_label' => 'Trigger AI Pipeline Inference',
                'sample_action_toast' => '✨ AI Workflow executed in 140ms! Structured JSON response generated.',
                'display_order' => 7,
                'is_active' => true,
            ],
            [
                'slug' => 'kothalipi',
                'category' => 'Bengali AI & Multimodal',
                'badge' => 'Language AI',
                'title' => 'KothaLipi AI Engine',
                'tagline' => 'Production-grade multimodal Bengali intelligence workspace unifying regional voice transcription, historical manuscript OCR, and Bangla Academy-standard writing.',
                'icon_name' => 'Languages',
                'mockup_title' => 'KothaLipi • Bengali Voice, Vision & Writing Engine',
                'live_url' => 'https://kothalipi.devcenterpoint.com',
                'admin_url' => null,
                'demo_username' => null,
                'demo_password' => null,
                'demo_role' => null,
                'stats' => [
                    ['label' => 'Regional Dialects', 'value' => '4 Native', 'change' => 'Sylhet → Chittagong', 'trend' => 'up'],
                    ['label' => 'Unified Workspaces', 'value' => '4 Modules', 'change' => 'Voice • Vision • Writing', 'trend' => 'up'],
                    ['label' => 'Orthography Standard', 'value' => '100%', 'change' => 'Bangla Academy Promito', 'trend' => 'up'],
                ],
                'activity_logs' => [
                    ['time' => 'Just now', 'event' => 'Sylhet dialect voice note transcribed & diarized with turn timestamps', 'badge' => 'কণ্ঠস্বর'],
                    ['time' => '2m ago', 'event' => 'Historical gazette scanned — conjunct ligatures preserved (ক্ষ, জ্ঞ, হ্ম)', 'badge' => 'নথি পাঠ'],
                    ['time' => '5m ago', 'event' => 'Essay proofread to Bangla Academy Promito & Sadhu ⇄ Cholit converted', 'badge' => 'শুদ্ধ লেখনী'],
                ],
                'business_outcomes' => [
                    'speedToMarket' => '2 to 4 weeks for domain tuning',
                    'impact' => 'Eliminates manual Bengali transcription & proofreading',
                    'security' => 'Firebase Auth with private Gemini inference',
                ],
                'client_benefits' => [
                    'Transcribes colloquial Sylhet, Chittagong, Noakhali and Dhaka speech into standardized Bengali with speaker diarization',
                    'Reads degraded manuscripts, gazettes and cursive handwriting while preserving complex যুক্তবর্ণ conjuncts',
                    'Enforces Bangla Academy Promito orthography with Sadhu ⇄ Cholit conversion and nine tonal rewrites',
                ],
                'deliverables' => [
                    'React 19 + Vite 8 multimodal PWA workspace (Voice, Vision, Writing, History)',
                    'Express + @google/genai backend exposing /api/ocr, /api/transcribe, /api/proofread, /api/summarize, /api/tts',
                    'Firebase Firestore & Google Auth cloud archive vault',
                    'Multi-format export studio — PDF, DOCX, Markdown and plain text',
                ],
                'sample_action_label' => 'Run Bengali OCR & Proofread',
                'sample_action_toast' => '✓ Bengali document OCR completed! Conjuncts preserved & proofread to Bangla Academy Promito.',
                'display_order' => 8,
                'is_active' => true,
            ],
        ];

        foreach ($solutions as $row) {
            SolutionProduct::updateOrCreate(['slug' => $row['slug']], $row);
        }
    }
}
